inhibit_all_warnings!
use_frameworks!

platform :ios, '10.0'

target 'HiClass_SDK' do
  pod 'HiClass_SDK', :path => '../'

  target 'HiClass_SDK_Tests' do
    inherit! :search_paths
    
  end
end

post_install do |installer|
  installer.pods_project.targets.each do |target|
    target.build_configurations.each do |config|
      config.build_settings['COMPILER_INDEX_STORE_ENABLE'] = "NO"
      config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '10.0'
    end
  end
  
  framework = installer.pods_project.frameworks_group["iOS"]["MobileCoreServices.framework"]
    framework.referrers.each do |ref|
      if ref.isa == "PBXBuildFile"
          ref.remove_from_project
      end
    end
  framework.remove_from_project
  
end
